apiVersion: apps/v1
kind: Deployment
metadata:
  name: remotedist
  labels:
    app: remotedist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remotedist
  template:
    metadata:
      labels:
        app: remotedist
    spec:
      containers:
      - name: remotedist
        image: docker.io/rsdias/fapesp:remotedist
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        - containerPort: 2010
---
apiVersion: v1
kind: Service
metadata:
  name: remotedist
spec:
  ports:
  - port: 8081
    name: tcp1
    targetPort: 8081
  - port : 2010
    name: tcp2
    targetPort: 2010
  selector:
    app: remotedist
  type: ClusterIP