apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  labels:
    app: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
    spec:
      containers:
      - name: distributor
        image: docker.io/rsdias/fapesp:distributor
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: distributor
spec:
  ports:
  - port: 8081
    name: tcp1
    targetPort: 8081
  - port: 5011
    name: tcp2
    targetPort: 5011
  - port: 5012
    name: tcp3
    targetPort: 5012
  - port: 5013
    name: tcp4
    targetPort: 5013
  - port: 5014
    name: tcp5
    targetPort: 5014
  selector:
    app: distributor
  type: LoadBalancer